### ISSUE TITLE
maven version is 1.1.3, not 1.1.2 in README.md

### ISSUE THREAD

**Issue by JesseBlackman** [yunpian/yunpian-java-sdk#1]
look here:  
http://mvnrepository.com/artifact/com.yunpian.sdk/yunpian-java-sdk  
please update it.

**Comment by dzh** [comment]
@JesseBlackman 嗯，README.md已更新，新版sdk1.2.0已发布，master是稳定分支，可直接构建使用，稍后会上传到maven。谢谢你的问题反馈！
