### ISSUE TITLE
1.2.x相比1.1.x变化太大了

### ISSUE THREAD

**Issue by ronankim** [yunpian/yunpian-java-sdk#12]
没有简略的使用文档吗？我看了下基本上完全不兼容1.1.x了啊

**Comment by ronankim** [comment]
SmsApi的所有子方法参数竟然都是Map，而且方法是用snake命名法，这是在是太诡异了吧？刚从js转学java吗？？？

**Comment by dzh** [comment]
1.考虑使用1.1.x的用户，所以保留了原来的YunpianRestClient。原来的代码有些问题，重写比较好。
2.用Map是为了参数扩展考虑
3.命令是为了api定义尽量一致，方便用户查找。

在评论前，先思考下别人为啥这么设计。希望你能贡献一个比这个更好的sdk。

**Comment by allenyuzhenlong** [comment]
@dzh 所有加@Deprecated注解的类和方法都是1.x版本的？都不建议用了吗？那API文档那边应该也要更新下。另外在代码示例那里有一个用 Apache httpclient 写的例子，那是建议用这个例子还是用 云片的sdk呢？谢谢！

**Comment by dzh** [comment]
@allenyuzhenlong 加@Deprecated基本上是1.1.x版本的功能，不建议使用，考虑有个过渡期所以保留，1.2.x的接口是完整的。 Apache httpclient的例子只是测试http功能，云片接口功能封装在YunpianClient里。今早看到，回晚了哈，项目首页有个README.md里有个QQ群，你可以加一下，群里看到及时些。

**Comment by ronankim** [comment]
@dzh 你想一下，用户自己的代码都是以正常Java命名规范命名的，而引入此sdk后的代码部分却混杂着snake命名的代码，你说这样是不是会造成用户这边的代码混乱？
