### ISSUE TITLE
为什么调用new SmsApi().single_send(params)会失败

### ISSUE THREAD

**Issue by allenyuzhenlong** [yunpian/yunpian-java-sdk#13]
Map<String, String> params = new HashMap<String, String>();
params.put("apikey", "xxxxxxxxxxxxxxxxxxx");
params.put("text", text);
params.put("mobile", mobile);
Result<SmsSingleSend> result = new SmsApi().single_send(params);

为什么会失败，失败的原因是YunpianApi 的uri()方法报空指针异常？还需要加什么参数呢？

**Comment by dzh** [comment]
new SmsApi()这种用户不对，应当
YunpianClient clnt = new YunpianClient("apikey");
clnt.init();
clnt.sms().single_send(params); 

参考README.md里的示例 @allenyuzhenlong
