### ISSUE TITLE
问题：使用了SDK之后系统日志输出跑到了tomcat目录之下，怎么改变呢？

### ISSUE THREAD

**Issue by rocbin** [yunpian/yunpian-java-sdk#18]
没有使用云片SDK之前，日志都在tomcat的logs目录下保存，单现在用了SDK，发现原先的配置没有用了，日志保存在tomcat目录下面了。

**Comment by dzh** [comment]
你用的老版还是新版SDK，新版SDK使用的slf4j日志接口，日志配置由应用自身的具体实现决定 @rocbin

**Comment by rocbin** [comment]
Oh! 我的还是1.1.1的版本。

**Comment by dzh** [comment]
1.2.x的api与老版不同，但迁移很简单。 @rocbin

**Comment by rocbin** [comment]
谢谢！
