### ISSUE TITLE
log4j配置文件被重置，导致项目本身的日志文件不再记录

### ISSUE THREAD

**Issue by zxmsdyz** [yunpian/yunpian-java-sdk#2]
common.Config.java中有强制重新设置log4j配置文件的static代码，建议去掉这块否则会对用户自身项目造成干扰，无法正常记录日志。

**Comment by linjiaqi86** [comment]
感谢反馈！我们在评估之后回复你

**Comment by dzh** [comment]
@zxmsdyz 新版sdk已发布，我们去掉了log4j的依赖，使用slf4j-api,感谢你的反馈!
