### ISSUE TITLE
少了签名API

### ISSUE THREAD

**Issue by CodinngLee** [yunpian/yunpian-java-sdk#4]

**Comment by dzh** [comment]
你好，是少了。过几天会发布一个新版sdk，那时候会补充。

**Comment by dzh** [comment]
新版sdk已发布，签名API已更新，谢谢你反馈问题。
添加签名参考代码如下：
YunpianClient clnt = new YunpianClient("apikey");
clnt.init();
clnt.sign().add(map)
clnt.close()
